def kFile = rootProject.file('local.properties')
def props = new Properties()
def storeFilePath = null
def storePassword = null
def keyAlias = null
def keyPassword = null

if (kFile.canRead()) {
    props.load(new FileInputStream(kFile))
    storeFilePath = props['SIGN_KEY_STORE_FILE']
    storePassword = props['SIGN_KEY_STORE_PASSWORD']
    keyAlias = props['SIGN_KEY_ALIAS']
    keyPassword = props['SIGN_KEY_PASSWORD']
} else {
    storeFilePath = System.getenv('SIGN_KEY_STORE_FILE')
    storePassword = System.getenv('SIGN_KEY_STORE_PASSWORD')
    keyAlias = System.getenv('SIGN_KEY_ALIAS')
    keyPassword = System.getenv('SIGN_KEY_PASSWORD')
}

if (storeFilePath) {
    android.signingConfigs.sign.storeFile file(storeFilePath)
    android.signingConfigs.sign.storePassword storePassword
    android.signingConfigs.sign.keyAlias keyAlias
    android.signingConfigs.sign.keyPassword keyPassword
} else {
    android.buildTypes.debug.signingConfig = android.signingConfigs.debug
}